-- +migrate Up
DROP TABLE IF EXISTS NotificationData;
CREATE TABLE NotificationData (
_notificationDataId INTEGER PRIMARY KEY AUTOINCREMENT,
notificationType INTEGER NOT NULL DEFAULT 1,
tripID INTEGER,
expirationTime INTEGER NOT NULL DEFAULT 0,
wasSent INTEGER NOT NULL DEFAULT 0,
wasUiDisabled INTEGER NOT NULL DEFAULT 0,
subject TEXT NOT NULL DEFAULT "",
message TEXT NOT NULL DEFAULT "",
shortMessage TEXT NOT NULL DEFAULT "",
FOREIGN KEY (tripID) REFERENCES Trips(_tripID)
);
ALTER TABLE Trips ADD COLUMN timeOverDue INT NOT NULL DEFAULT 0;